# Generated by Django 3.2 on 2022-08-19 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursereview',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='coursereview',
            name='text',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
    ]
