# Generated by Django 3.2 on 2022-08-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_reviews', '0002_auto_20220819_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursereview',
            name='address',
            field=models.CharField(default=False, max_length=254),
            preserve_default=False,
        ),
    ]
