# Generated by Django 3.2 on 2022-08-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_reviews', '0003_coursereview_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursereview',
            name='website',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
