# Generated by Django 3.2 on 2022-08-09 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_discounted_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discounted_price',
        ),
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
