# Generated by Django 3.2 on 2022-08-12 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_discounted_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='raiting',
            new_name='rating',
        ),
    ]
