# Generated by Django 3.2 on 2022-08-14 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_original_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='original_price',
            new_name='discounted_price',
        ),
    ]
