# Generated by Django 3.2 on 2022-08-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20220819_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_message',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
